### ISSUE TITLE
pfx

### ISSUE THREAD

**Issue by TheGuy68** [pouc/qlik-api-qrs#1]
what is this param?
pfx is this a string? file resource (require('pfx file'))? or what?
and "just getting https requires a pfx/pem certificate".

You lib "looks" good and appreciate the effort but if your going to put a lib online please put some explanations to the params etc.

**Comment by pouc** [comment]
look at the test file, it will give you a good idea on how this works
pfx is a buffer

this is on github & npm for my own usage as a dependency of other libs
no time to add comments
PRs are welcome

Best
